# Site Settings
title: resume stefan boicea
url: 'http://boicea.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Stefan Boicea
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Full stack developer, mostly focusing on helping clients increase their revenue through various optimisations 
of business processes. Solid analytical skills, simplifying complex problems.'

#sidebar links
email: stefanboicea@gmail.com
phone: +40 737 030 236
linkedin: stefanboicea
github: stefanboicea
twitter: '@stefanboicea'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113484853-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
